name: Issue → Hexo Post

on:
  issues:
    types: [labeled]     # only run when a label is added
  workflow_dispatch:      # manual run button (optional)

permissions:
  contents: write

jobs:
  build-post:
    runs-on: ubuntu-latest
    env:
      POSTS_DIR: blog/source/_posts
      SCRIPTS_DIR: blog/source/scripts
      DEFAULT_MODEL: gpt-5
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LOCAL_LLM_URL: ${{ secrets.LOCAL_LLM_URL }}
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}

    steps:
      - uses: actions/checkout@v4

      # Only proceed when the label added is exactly 'blog'
      - name: Guard: require 'blog' label
        if: ${{ github.event.label.name != 'blog' }}
        run: echo "Label '${{ github.event.label.name }}' ≠ 'blog' → exit." && exit 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r "$SCRIPTS_DIR/requirements.txt"

      - name: Generate post
        env:
          ISSUE_TITLE:  ${{ github.event.issue.title }}
          ISSUE_BODY:   ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO:         ${{ github.repository }}
        run: python "$SCRIPTS_DIR/generate_post.py"

      - name: Configure git author
        run: |
          git config user.name  "${GIT_AUTHOR_NAME:-github-actions[bot]}"
          git config user.email "${GIT_AUTHOR_EMAIL:-41898282+github-actions[bot]@users.noreply.github.com}"

      - name: Commit & push
        run: |
          mkdir -p "${POSTS_DIR}"
          git add "${POSTS_DIR}"
          git diff --cached --quiet || { git commit -m "blog: add (issue #${{ github.event.issue.number }})" && git push; }
